modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="amongius"
version="1.1.5"
displayName="Among Us Infection"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Earthquake101, MCreator"
description="Infects a portion of your world with the Amongwood Forest"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.amongius]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration